---
apiVersion: v1
kind: Secret
metadata:
  name: api
stringData:
  API_KEY: IMMUNOODLE_API_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: ClusterIP
  ports:
  - port: 5000
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: ghcr.io/immunoodle/data-portal-ingest-api:sha256-bf4ec71b51a7099f837e70a59047048447135d23268e6d694a040a1a7f54fd1b
          name: api
          env:
            - name: REDIS_AUTH
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: REDIS_AUTH
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: apikey
                  key: API_KEY
          ports:
            - containerPort: 5000
              name: http
