---
apiVersion: v1
kind: Secret
metadata:
  name: data-portal
stringData:
  DEX_CLIENT_SECRET: IMMUNOODLE_OAUTH_SECRET
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: data-portal
  annotations:
    cert-manager.io/cluster-issuer: intermediate-ca1-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: addslashbyredirect@file,data-portal-stripprefix@file
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/data-portal"
        backend:
          service:
            name: data-portal
            port:
              number: 3838
---
apiVersion: v1
kind: Service
metadata:
  name: data-portal
  labels:
    app: data-portal
spec:
  type: ClusterIP
  ports:
  - port: 3838
  selector:
    app: data-portal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-portal
  labels:
    app: data-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-portal
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: data-portal
    spec:
      volumes:
      - name: crt-mount
        secret:
          secretName: root-ca-secret
          items:
          - key: ca.crt
            path: ca.crt
      containers:
        - image: ghcr.io/immunoodle/data-portal:sha-6196384
          volumeMounts:
          - name: crt-mount
            mountPath: "/etc/secrets"
          name: data-portal
          env:
            - name: db
              value: "postgres"
            - name: db_host
              value: "postgresql"
            - name: RETICULATE_PYTHON
              value: "/opt/miniconda/envs/project_py_env/bin/python"
            - name: db_port
              value: "5432"
            - name: db_userid_x
              value: postgres
            - name: db_pwd_x
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              value: "postgres"
            - name: DB_HOST
              value: "postgresql"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: POSTGRES_PASSWORD
            - name: upload_template_path
              value: "/data/uploaded_templates"
            - name: upload_file_path
              value: "/data/associate_files"
            - name: blank_template_path
              value: "/data/review_templates"
            - name: immunoodle_api_key
              valueFrom:
                secretKeyRef:
                  name: apikey
                  key: API_KEY
            - name: SHINY_LOG_LEVEL
              value: DEBUG
            - name: SHINY_LOG_STDERR
              value: "1"
            - name: AWS_ACCESS_KEY_ID
              value: "root"
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: MINIO_ROOT_PASSWORD
            - name: AWS_DEFAULT_REGION
              value: us-east-1
            - name: S3_BUCKET_NAME
              value: data-portal
            - name: DEX_ISSUER
              value: "https://IMMUNOODLE_HOSTNAME/dex"
            - name: DEX_CLIENT_ID
              value: IMMUNOODLE_OAUTH_CLIENT_ID
            - name: DEX_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: data-portal
                  key: DEX_CLIENT_SECRET
            - name: APP_REDIRECT_URI
              value: "https://IMMUNOODLE_HOSTNAME/data-portal/"
            - name: HOSTNAME
              value: "https://IMMUNOODLE_HOSTNAME"
            - name: DEX_LOGOUT_ENDPOINT
              value: "https://IMMUNOODLE_HOSTNAME/data-portal/"
            - name: DEX_CA_CERT_PATH
              value: /etc/secrets/ca.crt
            - name: DEX_INTERNAL_URL
              value: "http://dex:5556/dex"
          ports:
          - containerPort: 3838
            name: shiny
