---
apiVersion: v1
kind: Secret
metadata:
  name: i-spi
stringData:
  DEX_CLIENT_SECRET: IMMUNOODLE_OAUTH_SECRET
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: i-spi
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: addslashbyredirect@file,i-spi-stripprefix@file
    cert-manager.io/cluster-issuer: intermediate-ca1-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/i-spi"
        backend:
          service:
            name: i-spi
            port:
              number: 3838
  tls:
  - hosts:
    - IMMUNOODLE_HOSTNAME
    secretName: cert-secret         
---
apiVersion: v1
kind: Service
metadata:
  name: i-spi
  labels:
    app: i-spi
spec:
  type: ClusterIP
  ports:
  - port: 3838
  selector:
    app: i-spi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: i-spi
  labels:
    app: i-spi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i-spi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: i-spi
    spec:
      containers:
        - image: ghcr.io/immunoodle/i-spi:main
          name: i-spi
# FIXME
#          resources:
#            requests:
#              cpu: "6"
#            limits:
#              cpu: "10"
          env:
            - name: db
              value: "postgres"
            - name: db_host
              value: "postgresql"
            - name: db_port
              value: "5432"
            - name: db_userid_x
              value: postgres
            - name: db_pwd_x
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: POSTGRES_PASSWORD
            - name: SHINY_LOG_LEVEL
              value: DEBUG
            - name: SHINY_LOG_STDERR
              value: "1"
#FIX ME
            - name: REDIRECT_URL
              value: ???

            - name: DEX_ISSUER
              value: "https://IMMUNOODLE_HOSTNAME/dex"
            - name: DEX_CLIENT_ID
              value: IMMUNOODLE_OAUTH_CLIENT_ID
            - name: DEX_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: data-portal
                  key: DEX_CLIENT_SECRET
            - name: APP_REDIRECT_URI
              value: https://IMMUNOODLE_HOSTNAME/i-spi/
          ports:
          - containerPort: 3838
            name: shiny
