---
apiVersion: v1
kind: Secret
metadata:
  name: ispi
stringData:
  DEX_CLIENT_SECRET: IMMUNOODLE_OAUTH_SECRET
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ispi
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: I-SPI-stripprefix@file
    cert-manager.io/cluster-issuer: intermediate-ca1-issuer
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/I-SPI"
        backend:
          service:
            name: ispi
            port:
              number: 3838
  tls:
  - hosts:
    - IMMUNOODLE_HOSTNAME
    secretName: cert-secret         
---
apiVersion: v1
kind: Service
metadata:
  name: ispi
  labels:
    app: ispi
spec:
  type: ClusterIP
  ports:
  - port: 3838
  selector:
    app: ispi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ispi
  labels:
    app: ispi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ispi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ispi
    spec:
      containers:
        - image: ghcr.io/immunoodle/i-spi:main
          name: ispi
# FIXME
#          resources:
#            requests:
#              cpu: "6"
#            limits:
#              cpu: "10"
          env:
            - name: db
              value: "postgres"
            - name: db_host
              value: "postgresql"
            - name: db_port
              value: "5432"
            - name: db_userid_x
              value: postgres
            - name: db_pwd_x
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: POSTGRES_PASSWORD
            - name: SHINY_LOG_LEVEL
              value: DEBUG
            - name: SHINY_LOG_STDERR
              value: "1"
#FIX ME
            - name: REDIRECT_URL
              value: ???

            - name: DEX_ISSUER
              value: "https://IMMUNOODLE_HOSTNAME/dex"
            - name: DEX_CLIENT_ID
              value: IMMUNOODLE_OAUTH_CLIENT_ID
            - name: DEX_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: data-portal
                  key: DEX_CLIENT_SECRET
            - name: APP_REDIRECT_URI
              value: https://IMMUNOODLE_HOSTNAME/i-spi
          ports:
          - containerPort: 3838
            name: shiny
