---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ispi
spec:
  encryptedData:
    AUTH0_KEY: 
    AUTH0_SECRET: 
    db_pwd_x: 
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: ispi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ispi
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: I-SPI-stripprefix@file
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/I-SPI"
        backend:
          service:
            name: ispi
            port:
              number: 3838
---
apiVersion: v1
kind: Service
metadata:
  name: ispi
  labels:
    app: ispi
spec:
  type: ClusterIP
  ports:
  - port: 3838
  selector:
    app: ispi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ispi
  labels:
    app: ispi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ispi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ispi
    spec:
      containers:
        - image: 
          name: ispi
          resources:
            requests:
              cpu: "6"
            limits:
              cpu: "10"
          env:
            - name: db
              value: "postgres"
            - name: db_host
              value: "postgres.immunoodle.local"
            - name: db_port
              value: "5432"
            - name: db_userid_x
              value: ???
            - name: db_pwd_x
              valueFrom:
                secretKeyRef:
                  name: ispi
                  key: db_pwd_x
            - name: AUTH0_USER
              value: ???
            - name: AUTH0_KEY
              valueFrom:
                secretKeyRef:
                  name: ispi
                  key: AUTH0_KEY
            - name: AUTH0_SECRET
              valueFrom:
                secretKeyRef:
                  name: ispi
                  key: AUTH0_SECRET
            - name: AUTH0_REMOTE_URL
              value: "https://immunoodle.local/"
            - name: SHINY_LOG_LEVEL
              value: DEBUG
            - name: SHINY_LOG_STDERR
              value: "1"
            - name: REDIRECT_URL
              value: ???
            - name: PGSSLCERT
              value: "/tmp/postgresql.crt"
            - name: DEX_ISSUER
              value: "https://immunoodle.local/dex"
            - name: DEX_CLIENT_ID
              value: ???
            - name: DEX_CLIENT_SECRET
              value: ???
            - name: APP_REDIRECT_URI
              value: https://immunoodle.local/
          ports:
          - containerPort: 3838
            name: shiny
