# TODO - Setup TLS
---
apiVersion: v1
kind: Secret
metadata:
  name: redis
stringData:
  REDIS_AUTH: IMMUNOODLE_REDIS_AUTH
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: redis:8
          name: redis
          args: ["--requirepass", "$(REDIS_AUTH)"]
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            # - name: REDIS_TLS_ENABLED
            #   value: "yes"
            # - name: REDIS_TLS_CERT_FILE
            #   value: /usr/local/etc/redis/redis.crt
            # - name: REDIS_TLS_KEY_FILE
            #   value: /usr/local/etc/redis/redis.key
            # - name: REDIS_TLS_CA_FILE
            #   value: /usr/local/etc/redis/ca.crt
            # - name: REDIS_TLS_PORT
            #   value: 6379
            - name: REDIS_AUTH
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: REDIS_AUTH
          ports:
            - containerPort: 6379
              name: redis
