---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "false"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: whoamiStickyCookie
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: 80
    - name: oauth2-proxy
      port: 8080
      targetPort: 8080
  selector:
    app: whoami
---
apiVersion: v1
kind: Secret
metadata:
  name: whoami
stringData:
  OAUTH2_PROXY_CLIENT_ID: IMMUNOODLE_WHOAMI_OAUTH_CLIENT_ID
  OAUTH2_PROXY_CLIENT_SECRET: IMMUNOODLE_WHOAMI_OAUTH_SECRET
  OAUTH2_PROXY_COOKIE_SECRET: IMMUNOODLE_OAUTH_COOKIE_SECRET
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/whoami"
        backend:
          service:
            name: whoami
            port:
              number: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  labels:
    app: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - name: whoami
        image: traefik/whoami
        ports:
        - name: web
          containerPort: 80
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.8.1
        env:
        - name: OAUTH2_PROXY_HTTP_ADDRESS
          value: 0.0.0.0:8080
        - name: OAUTH2_PROXY_UPSTREAMS
          value: http://localhost:80/
        - name: OAUTH2_PROXY_PROVIDER
          value: 'oidc'
        - name: OAUTH2_PROXY_PROVIDER_DISPLAY_NAME
          value: 'Authentication Server'
        - name: IMMUNOODLE_WHOAMI_OAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: whoami 
              key: IMMUNOODLE_WHOAMI_OAUTH_SECRET
        - name: IMMUNOODLE_WHOAMI_OAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: whoami
              key: IMMUNOODLE_WHOAMI_OAUTH_SECRET
        - name: OAUTH2_PROXY_EMAIL_DOMAINS
          value: '*'
        - name: OAUTH2_PROXY_PROXY_PREFIX
          value: '/whoami/oauth2'
        - name: OAUTH2_PROXY_COOKIE_PATH
          value: '/whoami'
        - name: OAUTH2_PROXY_REDIRECT_URL
          value: 'https://IMMUNOODLE_HOSTNAME/whoami/oauth2/callback'
        - name: OAUTH2_PROXY_OIDC_ISSUER_URL
          value: 'https://IMMUNOODLE_HOSTNAME/dex'
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: whoami
              key: OAUTH2_PROXY_COOKIE_SECRET
        - name: OAUTH2_PROXY_COOKIE_SECURE
          value: "true"
        - name: OAUTH2_PROXY_SKIP_CLAIMS_FROM_PROFILE_URL
          value: "true"
        - name: OAUTH2_PROXY_CODE_CHALLENGE_METHOD
          value: "S256"
        - name: OAUTH2_PROXY_PREFER_EMAIL_TO_USER
          value: "false"
        - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
          value: "true"
        - name: OAUTH2_PROXY_COOKIE_EXPIRE
          value: "0"
        - name: OAUTH2_PROXY_PROMPT
          value: "login"
        - name: OAUTH2_PROXY_SCOPE
          value: "openid profile email"
        # IF USING A SELF SIGNED CERT
        - name: OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY
          value: "true"
        ports:
        - containerPort: 8080
          name: oauth2-proxy

