---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worker
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: worker
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - image: ghcr.io/immunoodle/data-portal-ingest-worker:main
          name: worker
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: POSTGRES_PASSWORD
            - name: REDIS_AUTH
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: REDIS_AUTH
            - name: SQLALCHEMY_DATABASE_URL
              value: "postgresql://postgres:$(POSTGRES_PASSWORD)@postgresql.svc/postgres"
            - name: CELERY_BROKER_URL
              value: "redis://:$(REDIS_AUTH)@redis:6379/0"
            - name: CELERY_RESULT_BACKEND
              value: "redis://:$(REDIS_AUTH)@redis:6379/0"
          volumeMounts:
          - mountPath: /data
            name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: worker
